import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import'./globals.css';

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Fernando's Journal</title>
      <body className={`${urbanist.className}`}>{children}</body>
    </html>
  );
}
